### ISSUE TITLE
The code for input mask and attention mask

### ISSUE THREAD

**Issue by Qingkali** [haoyuc/MaskedDenoising#10]
Thanks for your code sharing, Could you tell me about the input mask and attention mask code?

**Comment by haoyuc** [comment]
Input mask: https://github.com/haoyuc/MaskedDenoising/blob/b4cb8edb51a87301fcb70039fb550fc6aca730ac/data/dataset_masked_denoising.py#L60

Attention mask:
https://github.com/haoyuc/MaskedDenoising/blob/b4cb8edb51a87301fcb70039fb550fc6aca730ac/models/network_swinir.py#L273

**Comment by Qingkali** [comment]
Thanks for your answer,it is helpful for me.
