### ISSUE TITLE
关于论文没有提及的细节的一些疑问

### ISSUE THREAD

**Issue by lovedoubledan** [haoyuc/MaskedDenoising#12]
1. baseline model是否指的就是图4的网络结构去掉input mask和attention mask？如果是，我是不是可以认为baseline model是在swinir的基础上修改后的模型？如果是，你们为什么不直接在swinir上使用input mask和attention mask？
2. 附加材料里说dropout模型是before the output convolutional layer of the baseline model，是在每个block的输出层前面 ，还是在整个网络的输出层前面？

**Comment by haoyuc** [comment]
1. 是的，baseline 其实就是去掉了 swinir 的 global residual
2. 是在整个网络的输出层前边，可以参考 "[Reflash dropout in image super-resolution](http://openaccess.thecvf.com/content/CVPR2022/html/Kong_Reflash_Dropout_in_Image_Super-Resolution_CVPR_2022_paper.html)" 这篇文章

**Comment by lovedoubledan** [comment]
好的，了解了，谢谢您的回复。
