### ISSUE TITLE
关于input mask代码的一点疑问

### ISSUE THREAD

**Issue by LowSingVz** [haoyuc/MaskedDenoising#13]
函数input_mask_with_noise好像是生成一个经过裁剪附加上mask的图像块，请问这是原论文中所指的mask token吗？那么利用mask token随机替换原图像中像素的代码在哪呢？十分感谢！

**Comment by haoyuc** [comment]
Hi！我们使用了一种比较简单的实现方法，在网络的一开始我们使用了一个 1*1 的卷积，由于 input_mask_with_noise 已经把 mask 的位置变为统一的固定值，配合使用 bias 的 1*1 的卷积，可以将 mask 后的固定值变为 mask token。这样的实现比较方便地实现了同等的目标。

**Comment by LowSingVz** [comment]
感谢您的回答！
