### ISSUE TITLE
关于权重的问题

### ISSUE THREAD

**Issue by Alex-Wula** [haoyuc/MaskedDenoising#18]
您好！请问您提供的权重（在model_zoo中）是只能处理gaussain noise 吗？如果我想处理其它噪声，我是否需要重新训练？

**Comment by haoyuc** [comment]
我们这个实验的模型主要是为了模拟在极端情况下（例如训练集噪声仅有 gaussain noise，并且 level 是固定的 15），如何提高模型的泛化能力，因此并不一定适合 real-world 的应用。

如果想处理其他噪声，重新训练性能肯定更好，如果不重新训练的话，我们当前模型的性能一定优于不使用 masked training 的其他（同样是只在 gaussain noise，level 15 上训练的）模型。

**Comment by Alex-Wula** [comment]
好的，谢谢您的解答！
