### ISSUE TITLE
loss caused by the mask operation

### ISSUE THREAD

**Issue by AAlkaid** [haoyuc/MaskedDenoising#2]
I have seen one paper using the crop and paste operation(crop some part from one image and paste it on the origin image) to enhance the performance. Im not sure if it works in this situation. Just a possible solution~hhhh

**Comment by haoyuc** [comment]
We sincerely thank you for your attention and discussion of our work.  And we appreciate your suggestion of using the crop and paste operation to enhance performance. This provides us with some inspiration. Thank you for taking the time to share this idea with us!
