### ISSUE TITLE
what command can be image denoising? 

### ISSUE THREAD

**Issue by lhehejunl** [haoyuc/MaskedDenoising#8]
Hi,Bro,thanks you for your code.
can you tell me the command for image denoising?
for exemple, i have a noise image, i have no clean image, now, i wanna to denoising. 
your command: 
python main_test_swinir.py \
        --model_path model_zoo/input_mask_80_90.pth  \
        --name input_mask_80_90/McM_poisson_20  \
        --opt model_zoo/input_mask_80_90.json \
        --folder_gt testset/McM/HR  \
        --folder_lq testset/McM/McM_poisson_20

but, i have only one noise image, if i use:
python main_test_swinir.py \
        --model_path model_zoo/input_mask_80_90.pth  \
        --name input_mask_80_90/McM_poisson_20  \
        --opt model_zoo/input_mask_80_90.json \
        --folder_gt testset/mynoiseImg
will be output some fault

**Comment by lhehejunl** [comment]
> Hi,Bro,thanks you for your code. can you tell me the command for image denoising? for exemple, i have a noise image, i have no clean image, now, i wanna to denoising. your command: python main_test_swinir.py --model_path model_zoo/input_mask_80_90.pth --name input_mask_80_90/McM_poisson_20 --opt model_zoo/input_mask_80_90.json --folder_gt testset/McM/HR --folder_lq testset/McM/McM_poisson_20
> 
> but, i have only one noise image, if i use: python main_test_swinir.py --model_path model_zoo/input_mask_80_90.pth --name input_mask_80_90/McM_poisson_20 --opt model_zoo/input_mask_80_90.json --folder_gt testset/mynoiseImg will be output some faults

------------------------------
i use following command get the result of denoising:
 python main_test_swinir.py
--model_path model_zoo/input_mask_80_90.pth
--name input_mask_80_90/McM_poisson_20
--opt model_zoo/input_mask_80_90.json
--folder_gt testset/mynoiseImg
--folder_lq testset/mynoiseImg

Is right?

**Comment by haoyuc** [comment]
Yes, you can use this command, it could work.
